---
- name: Redhat | Install openssh-server
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - openssh-server
      - openssh-clients

- name: Redhat | Check Host key
  ansible.builtin.stat:
    path: /etc/ssh/{{ item }}
  loop:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ed25519_key
  register: centos_host_keys

- name: Redhat | ssh-keygen
  ansible.builtin.command: /usr/bin/ssh-keygen -A
  args:
    creates: "{{ item }}"
  when: not item.stat.exists
  loop: "{{ centos_host_keys.results }}"
  tags:
    - molecule-idempotence-notest
